receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    resource_to_telemetry_conversion:
      enabled: true
  logging:
    verbosity: detailed

processors:
  batch:
  resourcedetection/docker:
    detectors: [env, docker]

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resourcedetection/docker]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch, resourcedetection/docker]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch, resourcedetection/docker]
      exporters: [logging]