version: "3.9"
services:
  sampling:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "5051:5051"
    environment:
      - ASPNETCORE_URLS=http://+:5051
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcollector:4317
  otelcollector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./configs/otel-collector-config.yml:/etc/otel-collector-config.yml
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14250:14250"
      - "14268:14268"
      - "6831:6831/udp"
      - "16686:16686"
      - "16685:16685"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus-otel.yml:/etc/prometheus/prometheus.yml
      - ./tmp/prometheus:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - otelcollector
