{
 "title": ".NET runtime metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Throughput, rps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_route, http_status_code, http_method) (rate(http_server_duration_count{http_route!=\"\"}[$__rate_interval]))",
     "legendFormat": "[{{http_method}}]  {{http_route}} - {{http_status_code}}"
    }
   ]
  },
  {
   "title": "CPU, %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "avg by (state) (rate(process_cpu_time[$__rate_interval])) * 100",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Contention rate per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (rate(process_runtime_dotnet_monitor_lock_contention_count[5m]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_size",
     "legendFormat": "{{generation}}"
    },
    { "expr": "process_memory_usage", "legendFormat": "physical memory" }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "max by (job, instance) (process_threads)",
     "legendFormat": "max thread count"
    },
    {
     "expr": "avg by (job) (process_runtime_dotnet_thread_pool_threads_count)",
     "legendFormat": "avg thread pool threads"
    },
    {
     "expr": "max by (job, instance) (process_runtime_dotnet_thread_pool_queue_length)",
     "legendFormat": " max thread pool queue length"
    }
   ]
  },
  {
   "title": "Server latency, ms, P95",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": " histogram_quantile(0.95, sum(rate(http_server_duration_bucket{http_route!=\"\"}[$__rate_interval])) by (le, http_route, http_method)) ",
     "legendFormat": "p95 {{http_method}} {{http_route}}"
    },
    {
     "expr": " histogram_quantile(0.5, sum(rate(http_server_duration_bucket{http_route!=\"\"}[$__rate_interval])) by (le, http_route, http_method)) ",
     "legendFormat": "p50  {{http_method}} {{http_route}}"
    }
   ]
  },
  { "gridPos": { "h": 7, "w": 9, "x": 9, "y": 13 } },
  {
   "title": "Error rate per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (http_status_code, http_route, job) (rate(http_server_duration_count{http_status_code!=\"200\",http_status_code!=\"201\"}[$__rate_interval]))",
     "legendFormat": "{{http_route}} - {{http_status_code}}"
    },
    {
     "expr": "rate(process_runtime_dotnet_exceptions_count[$__rate_interval])",
     "legendFormat": "exception rate"
    }
   ]
  }
 ]
}