{
 "title": "Database and cache",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Redis memory usage, MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "redis_memory_used_bytes / 1024 / 1024",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_rss_bytes / 1024 / 1024",
     "legendFormat": "rss"
    },
    {
     "expr": "redis_memory_peak_bytes / 1024 / 1024",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "Redis CPU, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "100 * sum by (state) (rate(redis_cpu_time_seconds_total [$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "targets": [
    { "expr": "redis_uptime_seconds_total ", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Key eviction and expire rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(redis_keys_evicted_total[$__rate_interval])",
     "legendFormat": "evicted"
    },
    {
     "expr": "rate(redis_keys_expired_total[$__rate_interval])",
     "legendFormat": "expired"
    }
   ]
  },
  {
   "title": "Redis hit rate, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "100 * sum by (net_peer_name) (rate(db_operation_duration_milliseconds_count{db_operation=\"GetString\",db_system=\"redis\",cache_hit=\"true\"} [$__rate_interval])) / sum by (net_peer_name)  (rate(db_operation_duration_milliseconds_count{db_operation=\"GetString\",db_system=\"redis\",db_redis_status=\"ok\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mongo request rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum by (db_mongodb_collection, db_name, db_operation) (rate(db_operation_duration_milliseconds_count{db_mongodb_status=\"ok\",db_system=\"mongodb\"}[$__rate_interval]))",
     "legendFormat": "{{db_name}}.{{db_mongodb_collection}} - {{db_operation}}"
    }
   ]
  },
  {
   "title": " Command rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_processed_total [1m]))",
     "legendFormat": "commands"
    }
   ]
  },
  {
   "title": "Hit and miss rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "sum (rate(redis_keyspace_hits_total[$__rate_interval]))",
     "legendFormat": "hit rate"
    },
    {
     "expr": "sum (rate(redis_keyspace_misses_total[$__rate_interval]))",
     "legendFormat": "miss rate"
    }
   ]
  },
  {
   "title": "Error rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "sum by (db_name, db_mongodb_collection, db_operation, db_mongodb_status) (rate(db_operation_duration_milliseconds_count{db_mongodb_status!=\"ok\",db_system=\"mongodb\"}[$__rate_interval]))",
     "legendFormat": "{{db_mongodb_collection}} - {{db_operation}} - {{db_mongodb_status}}"
    },
    {
     "expr": "sum by (db_operation, db_redis_status) (rate( db_operation_duration_milliseconds_count{db_redis_status!=\"ok\",db_system=\"redis\"}[$__rate_interval]))",
     "legendFormat": "redis - {{db_operation}} - {{db_redis_status}}"
    }
   ]
  },
  {
   "title": "Failure call duration, P95 ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_operation_duration_milliseconds_bucket{db_mongodb_status!=\"ok\"}[$__rate_interval])) by (le, net_peer_name, db_mongodb_status))",
     "legendFormat": "p95 {{net_peer_name}} {{db_mongodb_status}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_operation_duration_milliseconds_bucket{db_redis_status!=\"ok\"}[$__rate_interval])) by (le, net_peer_name, db_redis_status))",
     "legendFormat": "p95 {{net_peer_name}} {{db_redis_status}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(db_operation_duration_milliseconds_bucket{db_redis_status!=\"ok\"}[$__rate_interval])) by (le, net_peer_name, db_redis_status))",
     "legendFormat": "p50 {{net_peer_name}} {{db_redis_status}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(db_operation_duration_milliseconds_bucket{db_mongodb_status!=\"ok\"}[$__rate_interval])) by (le, net_peer_name, db_mongodb_status))",
     "legendFormat": "p50 {{net_peer_name}} {{db_mongodb_status}}"
    }
   ]
  },
  {
   "title": "Successful call duration, P95 ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_operation_duration_milliseconds_bucket{db_mongodb_status=\"ok\"}[$__rate_interval])) by (le, net_peer_name))",
     "legendFormat": "mongo p95 {{net_peer_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_operation_duration_milliseconds_bucket{db_redis_status=\"ok\"}[$__rate_interval])) by (le, net_peer_name))",
     "legendFormat": "redis p95 {{net_peer_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(db_operation_duration_milliseconds_bucket{db_redis_status=\"ok\"}[$__rate_interval])) by (le, net_peer_name))",
     "legendFormat": "redis p50 {{net_peer_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(db_operation_duration_bucket{db_mongodb_status=\"ok\"}[$__rate_interval])) by (le, net_peer_name))",
     "legendFormat": "mongo p50 {{net_peer_name}}"
    }
   ]
  }
 ]
}