version: "3.9"
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5051:5051"
    depends_on:
      - storage
    environment:
      - Storage__Endpoint=http://storage:5050
      - ASPNETCORE_URLS=http://+:5051
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcollector:4317
      - OTEL_RESOURCE_ATTRIBUTES=region=westus,tag=foo
      - Sampling_Probability=1.0
  storage:
    build:
      context: ./
      dockerfile: ./storage/Dockerfile
    ports:
      - "5050:5050"
    environment:
      - ASPNETCORE_URLS=http://+:5050
      - OTEL_RESOURCE_ATTRIBUTES=region=westus,tag=bar,env=Production
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcollector:4317
      # for demo purposes only, make sure to pass environment securely
      - ConnectionStrings__MySql=server=mysql;user=root;password=pwd;database=memes
  mysql:
    image: docker.io/bitnami/mysql:8.0.33
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      # for demo purposes only, make sure to pass environment securely
      - MYSQL_ROOT_PASSWORD=pwd
  otelcollector:
    user: "1001" #change to your user id if running on WSL (or give 1001 ownership over /var/run/docker.sock)
    image: otel/opentelemetry-collector-contrib:0.78.0
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./configs/otel-collector-config.yml:/etc/otel-collector-config.yml
    depends_on:
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.45.0
    ports:
      - "14250:14250"
      - "14268:14268"
      - "6831:6831/udp"
      - "16686:16686"
      - "16685:16685"
  prometheus:
    image: prom/prometheus:v2.44.0
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - otelcollector

volumes:
  mysql_data:
    driver: local
