{
 "title": "Azure Storage Queues dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Sent, receive, and successful processing message rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (net_peer_name, messaging_destination_name) (rate(messaging_azqueues_publish_duration_milliseconds_count{messaging_azqueue_status=\"ok\"}[$__rate_interval]))",
     "legendFormat": "sent to {{net_peer_name}}/{{messaging_destination_name}}"
    },
    {
     "expr": "sum by (net_peer_name, messaging_source_name) (rate(messaging_azqueues_consumer_lag_seconds_count[$__rate_interval]))",
     "legendFormat": "received - {{net_peer_name}}/{{messaging_source_name}}"
    },
    {
     "expr": "sum by (net_peer_name, messaging_source_name) (rate(messaging_azqueues_process_message_duration_milliseconds_count{messaging_azqueue_status=\"ok\"}[$__rate_interval]))",
     "legendFormat": "processed - {{net_peer_name}}/{{messaging_source_name}}"
    }
   ]
  },
  {
   "title": "Consumer lag, sec, P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_azqueues_consumer_lag_seconds_bucket[$__rate_interval])) by (le, messaging_source_name, net_peer_name)) ",
     "legendFormat": "{{net_peer_name}}/{{messaging_source_name}}"
    }
   ]
  },
  {
   "title": "Error rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum by (net_peer_name, messaging_destination_name, messaging_azqueue_status) (rate(messaging_azqueues_publish_duration_milliseconds_count{messaging_azqueue_status!=\"ok\"}[$__rate_interval]))",
     "legendFormat": "send {{net_peer_name}}/{{messaging_destination_name}} - {{messaging_azqueue_status}}"
    },
    {
     "expr": "sum by (net_peer_name, messaging_source_name, messaging_azqueue_status) (rate(messaging_azqueues_process_loop_duration_milliseconds_count{messaging_azqueue_status=\"fail\"}[$__rate_interval]))",
     "legendFormat": "batch process {{net_peer_name}}/{{messaging_source_name}} - {{messaging_azqueue_status}}"
    },
    {
     "expr": "sum by (net_peer_name, messaging_source_name, messaging_azqueue_status) (rate(messaging_azqueues_process_message_duration_milliseconds_count{messaging_azqueue_status!=\"ok\"}[$__rate_interval]))",
     "legendFormat": "message process {{net_peer_name}}/{{messaging_source_name}} - {{messaging_azqueue_status}}"
    }
   ]
  },
  {
   "title": "Send duration, ms, P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_azqueues_publish_duration_milliseconds_bucket[$__rate_interval])) by (le, messaging_destination_name, net_peer_name, messaging_azqueue_status)) ",
     "legendFormat": "{{net_peer_name}}/{{messaging_destination_name}} - {{messaging_azqueue_status}}"
    }
   ]
  },
  {
   "title": "Approximate queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "max by (net_peer_name, messaging_source_name) (messaging_azqueues_queue_size_messages)",
     "legendFormat": "{{net_peer_name}}/{{messaging_source_name}}"
    }
   ]
  },
  {
   "title": "Average received batch size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum by (net_peer_name, messaging_source_name) (rate(messaging_azqueues_process_message_duration_milliseconds_count[$__rate_interval])) / sum by (net_peer_name, messaging_source_name) (rate(messaging_azqueues_process_loop_duration_milliseconds_count{messaging_azqueues_status!=\"empty\"}[$__rate_interval])) ",
     "legendFormat": "{{net_peer_name}}/{{messaging_source_name}}"
    }
   ]
  },
  {
   "title": "Process loop duration, ms, P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_azqueues_process_loop_duration_milliseconds_bucket[$__rate_interval])) by (le, messaging_source_name, net_peer_name, messaging_azqueue_status)) ",
     "legendFormat": "{{net_peer_name}}/{{messaging_source_name}} - {{messaging_azqueue_status}}"
    }
   ]
  },
  {
   "title": "Process message duration, ms, P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(messaging_azqueues_process_message_duration_milliseconds_bucket[$__rate_interval])) by (le, messaging_source_name, net_peer_name, messaging_azqueue_status)) ",
     "legendFormat": "{{net_peer_name}}/{{messaging_source_name}} - {{messaging_azqueue_status}}"
    }
   ]
  },
  {
   "title": "No messages received, rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(messaging_azqueues_process_loop_duration_milliseconds_count{messaging_azqueue_status=\"empty\"}[$__rate_interval])) by (net_peer_name, messaging_source_name)",
     "legendFormat": "{{net_peer_name}}/{{messaging_source_name}}"
    }
   ]
  },
  {
   "title": "HTTP client request duration, ms, P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_duration_milliseconds_bucket[$__rate_interval])) by (net_peer_name, service_name, le, http_method, http_status_code))",
     "legendFormat": "{{service_name}} to {{net_peer_name}} - [{{http_method}}] {{http_status_code}}"
    }
   ]
  },
  {
   "title": "HTTP request rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_client_duration_milliseconds_count[$__rate_interval])) by (net_peer_name, http_status_code, service_name, http_method)",
     "legendFormat": "{{service_name}} to {{net_peer_name}} - [{{http_method}}] {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Instance count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 24 },
   "targets": [
    {
     "expr": "count(count(process_cpu_time_seconds_total) by (service_instance_id, service_name)) by (service_name)",
     "legendFormat": "{{servic_name}}"
    }
   ]
  },
  {
   "title": "Processing loop, rate per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(messaging_azqueues_process_loop_duration_milliseconds_count[$__rate_interval])) by (messaging_source_name, messaging_azqueue_status)",
     "legendFormat": "{{messaging_source_name}} - {{messaging_azqueue_status}}"
    }
   ]
  }
 ]
}